[tasks.default]
deps = ["alacritty", "sway", "games", "nvim", "hardware"]

[macros.install]
deps = ["yay"]
prefix = ["yay", "-S"]

[tasks.yay]
deps = ["git"]
rejects = [["which", "yay"]]
cmds = [
	["${HM_SRC}/bin/install_yay.sh"]
]

[tasks.git]
cmds = [
	["sudo", "pacman", "-S", "git", "git-lfs", "openssh"]
]
links = [
	[".gitconfig"]
]

[tasks.fonts]
cmds = [
	["@install", "ttf-liberation", "ttf-font-awesome"]
]

[tasks.alacritty]
deps = ["fish", "tmux"]
cmds = [
	["@install", "alacritty"]
]
links = [
	[".config/alacritty"]
]

[tasks.fish]
cmds = [
	["@install", "fish", "fisher", "fzf"]
]
links = [
	[".config/fish"]
]

[tasks.tmux]
cmds = [
	["@install", "tmux", "tmuxp"]
]
links = [
	[".config/tmux"]
]

[tasks.pywal]
cmds = [
	["@install", "python-pywal", "python-colorthief"],
	["wal", "-i", "${HM_SRC}/wallpaper.jpg", "--backend", "colorthief"]
]

[tasks.sway]
cmds = [
	["gpg", "--search-keys", "A1774C1B37DC1DCEDB65EE469B8450B91D1362C1"],
	["gpg", "--lsign-key", "A1774C1B37DC1DCEDB65EE469B8450B91D1362C1"],
	["@install", "xorg-server-xwayland", "sway", "swayidle", "swaylock", "waybar", "mako", "bemenu", "j4-dmenu-desktop", "jq", "grim", "slurp", "wl-clipboard", "xdg-user-dirs", "blueshift"],
	["xdg-user-dirs-update"]
]
deps = ["pywal", "fonts", "amdgpu", "audio", "browsers", "chat"]
links = [
	[".config/sway"],
	[".config/waybar"],
	[".config/mako"]
]

[tasks.i3]
cmds = [
	["@install", "i3-gaps", "polybar"]
]
deps = ["pywal", "fonts", "amdgpu", "audio", "browsers", "chat"]
links = [
	[".config/i3"],
	[".config/polybar"]
]

[tasks.nvim]
cmds = [
	["@install", "neovim", "python-neovim"]
]
links = [
	[".config/nvim"]
]

[tasks.audio]
cmds = [
	["@install", "pulseaudio", "pamixer", "pavucontrol"]
]
links = [
	[".alsoftrc"]
]

[tasks.browsers]
cmds = [
	["@install", "google-chrome", "firefox"]
]

[tasks.chat]
cmds = [
	["@install", "discord", "pidgin", "purple-facebook", "telegram-purple", "purple-battlenet-hg", "purple-discord-git", "purple-hangouts-hg"]
]

[tasks.hardware]
cmds = [
	["@install", "ckb-next", "corectrl", "openrgb", "liquidctl"]
]
links = [
	[".config/OpenRGB"]
]

[tasks.games]
cmds = [
	["@install", "steam", "steam-native-runtime", "lutris", "wine", "retroarch", "multimc5", "oversteer", "mangohud", "goverlay", "gamemode"]
]

[tasks.amdgpu]
cmds = [
	["@install", "mesa", "lib32-mesa", "vulkan-radeon", "lib32-vulkan-radeon", "vulkan-icd-loader", "lib32-vulkan-icd-loader", "amdvlk", "lib32-amdvlk"]
]

[tasks.music]
cmds = [
	["@install", "mpc", "ncmpcpp", "cli-visualizer"]
]
links = [
	[".config/mopidy"],
	[".config/vis"]
]
